### ISSUE TITLE
How do you define doublet rate accurately?

### ISSUE THREAD

**Issue by smk5g5** [xnnba1984/DoubletCollection#2]
Hi,

I am trying to use your tool for predicting doublets in my data.
When I use doublet rate for my 10x data using the recommendations here https://uofuhealth.utah.edu/huntsman/shared-resources/gba/htg/single-cell/genomics-10x.php
 I get a few predicted doublets.
doublet_results <- FindDoublets(score.list=score.list,rate=0.08)

But when I use an approach to correct it for the number of cells as described here https://jef.works/blog/2017/12/14/barcode-doublets/ I get no results i.e. empty vector.

I was wondering  if there is a better way to define or get doublet rate based on one's data?

Thanks!

**Comment by xnnba1984** [comment]
Thank you for using this tool. 

Besides the recommendation from the sequencing platform, you can also check the distribution of doublet scores. If there is a bimodal distribution, then the cutoff of the doublet score can be selected in the middle of these two models. 

Another way is to try different doublet rates and check the downstream analysis, like cell clustering. A good rate should generate downstream analysis consistent with validated biological conclusions.

Hope that helps!
